modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/SkinnedCarts/issues"
license="MIT"

[[mods]]
modId="skinnedcarts"
version="${file.jarVersion}"
displayName="Skinned Carts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skinned-carts"
authors="Mrbysco"
description='''
Adding Minecarts with skins.
'''
credits="Gentleman_Gnu for the idea"
[[dependencies.skinnedcarts]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.skinnedcarts]]
modId="neoforge"
mandatory=true
versionRange="[20.2.64-beta,)"
ordering="NONE"
side="BOTH"