modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/SkinnedCarts/issues"
license="MIT"

[[mods]]
modId="skinnedcarts"
version="${file.jarVersion}"
displayName="Skinned Carts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skinned-carts"
authors="Mrbysco"
description='''
Adding Minecarts with skins.
'''
credits="Gentleman_Gnu for the idea"
[[dependencies.skinnedcarts]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.skinnedcarts]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"