modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Mrbysco/SkinnedCarts"
license="MIT"

[[mods]]
modId="skinnedcarts"
version="${file.jarVersion}"
displayName="Skinned Carts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skinned-carts"
authors="Mrbysco"
description='''
Adding Minecarts with skins.
'''
credits="Gentleman_Gnu for the idea"
[[dependencies.skinnedcarts]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"