modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/SkinnedCarts/issues"
license="MIT"

[[mods]]
modId="skinnedcarts"
version="${file.jarVersion}"
displayName="Skinned Carts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/skinned-carts"
authors="Mrbysco"
description='''
Adding Minecarts with skins.
'''
credits="Gentleman_Gnu for the idea"
[[dependencies.skinnedcarts]]
modId="minecraft"
type="required"
versionRange="[1.21.5,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.skinnedcarts]]
modId="neoforge"
type="required"
versionRange="[21.5.0-beta,)"
ordering="NONE"
side="BOTH"